version: '3.9'
services:
  db:
    image: postgres
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Backery2
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
  web:
    restart: always
    build: .
    command: bash -c "python ./backeryBackend/manage.py makemigrations &&
                      python ./backeryBackend/manage.py migrate &&
                      python ./backeryBackend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db